pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--6.org.readthedocs.build/en/6/

chore(release): bump to 0.0.1

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--7.org.readthedocs.build/en/7/

chore(release): bump to 1.0.0

---

.github/workflows/wheels.yml
pyproject.toml

Fixes #8
----
📚 Documentation preview 📚: https://pybwa--9.org.readthedocs.build/en/9/

fix: add c-headers to the wheel

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--10.org.readthedocs.build/en/10/

chore(release) bump to 1.0.1

---

.github/workflows/tests.yml

----
📚 Documentation preview 📚: https://pybwa--11.org.readthedocs.build/en/11/

ci: update the cache action to v4

---

build.py
pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--12.org.readthedocs.build/en/12/

fix: typo in package_dirs

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--13.org.readthedocs.build/en/13/

chore(release): bump to 1.0.2

---

.github/workflows/publish_pybwa.yml

----
📚 Documentation preview 📚: https://pybwa--14.org.readthedocs.build/en/14/

ci: publish to checkout the bwa submodule

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--15.org.readthedocs.build/en/15/

chore(release): bump to 1.0.3

---

.github/workflows/wheels.yml

----
📚 Documentation preview 📚: https://pybwa--22.org.readthedocs.build/en/22/

 remove macos arm64 wheels support for now

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--23.org.readthedocs.build/en/23/

chore(release): bump to 1.0.4

---

pybwa/libbwaaln.pxd
pybwa/libbwaaln.pyi
pybwa/libbwaaln.pyx
pybwa/libbwaaln_utils.c
pybwa/libbwaaln_utils.h
tests/test_bwapy.py

feat: add threading support to bwa aln

---

README.md

----
📚 Documentation preview 📚: https://pybwa--16.org.readthedocs.build/en/16/

chore: update badges in main README

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--26.org.readthedocs.build/en/26/

chore(release): bump to 1.1.0

---

build.py
pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--29.org.readthedocs.build/en/29/

fix: include the bwa patches in the distributions

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--30.org.readthedocs.build/en/30/

chore(release): bump to 1.1.1

---

build.py

----
📚 Documentation preview 📚: https://pybwa--31.org.readthedocs.build/en/31/

fix: support building a wheels when not in the git repo

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--32.org.readthedocs.build/en/32/

chore(release): bump to 1.1.2

---

build.py

----
📚 Documentation preview 📚: https://pybwa--33.org.readthedocs.build/en/33/

fix: fix build from source

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--34.org.readthedocs.build/en/34/

chore(release): bump to 1.1.3

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--45.org.readthedocs.build/en/45/

chore(release): bump to 1.4.2

---

.github/workflows/tests.yml
build.py
poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--47.org.readthedocs.build/en/47/

ci: add code coverage of cython files

---

.github/workflows/wheels.yml
ci/linux-deps
ci/osx-deps

----
📚 Documentation preview 📚: https://pybwa--48.org.readthedocs.build/en/48/

ci: fix wheels build for osx

---

pybwa/libbwamem.pxd

----
📚 Documentation preview 📚: https://pybwa--49.org.readthedocs.build/en/49/

chore: fix compiler warnings lin pybwa/libbwamem.pyd

---

pybwa/libbwaindex.pyx
tests/test_libbwaindex.py

Alternate to https://github.com/fulcrumgenomics/pybwa/pull/56 which adds tests
----
📚 Documentation preview 📚: https://pybwa--57.org.readthedocs.build/en/57/

fix: str paths failed with BwaIndex.index

---

README.md

----
📚 Documentation preview 📚: https://pybwa--61.org.readthedocs.build/en/61/

chore: add doi to README

---

.github/workflows/tests.yml
build.py

----
📚 Documentation preview 📚: https://pybwa--65.org.readthedocs.build/en/65/

chore: add fast fail for tests and parallelize extension builds

---

pybwa/libbwaaln.pxd
pybwa/libbwaindex.pxd
pybwa/libbwamem.pxd

----
📚 Documentation preview 📚: https://pybwa--66.org.readthedocs.build/en/66/

chore: add const to various C imports

---

.github/workflows/tests.yml
.github/workflows/wheels.yml

Also, change `save-output` to `GITHUB_OUTPUT`.
Fixes #55 .
----
📚 Documentation preview 📚: https://pybwa--70.org.readthedocs.build/en/70/

chore: add pybwa version to the wheel name and suffix .whl

---

.github/workflows/tests.yml

Fixes: https://github.com/fulcrumgenomics/pybwa/issues/79
----
📚 Documentation preview 📚: https://pybwa--81.org.readthedocs.build/en/81/

chore: update tests on push

---

build.py

----
📚 Documentation preview 📚: https://pybwa--83.org.readthedocs.build/en/83/

chore: update classifiers in build

---

pyproject.toml

Tested by building then installing an sdist locally.
----
📚 Documentation preview 📚: https://pybwa--85.org.readthedocs.build/en/85/

fix: add missing htslib source files

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--87.org.readthedocs.build/en/87/

chore(release): bump to 1.6.0

---

build.py

See failure here: https://github.com/bioconda/bioconda-recipes/actions/runs/14201778001/job/39790281309
See success here: https://github.com/bioconda/bioconda-recipes/actions/runs/14205762536/job/39803089911
----
📚 Documentation preview 📚: https://pybwa--92.org.readthedocs.build/en/92/

fix: always configure in htslib

---

.github/workflows/publish_pybwa.yml

----
📚 Documentation preview 📚: https://pybwa--97.org.readthedocs.build/en/97/

chore: update git-cliff CI action to v4

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--99.org.readthedocs.build/en/99/

fix: fix the body for the git-cliff changelog

---

build.py
patches/0005-feat-adding-support-for-SAM-BAM-output-using-htslib.patch

Fixes: https://github.com/fulcrumgenomics/pybwa/issues/100
----
📚 Documentation preview 📚: https://pybwa--101.org.readthedocs.build/en/101/

Detect and optionally build with curl, deflate, lzma, and bz2

---

README.md

----
📚 Documentation preview 📚: https://pybwa--103.org.readthedocs.build/en/103/

doc: fix links to logo

---

pybwa/libbwaaln.pyx
pybwa/libbwaindex.pyx
pybwa/libbwamem.pyx

Thanks @clintval for spotting this
----
📚 Documentation preview 📚: https://pybwa--105.org.readthedocs.build/en/105/

feat: remove types arguments

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--108.org.readthedocs.build/en/108/

chore(release): bump to 2.1.0

---

pyproject.toml

----
📚 Documentation preview 📚: https://pybwa--113.org.readthedocs.build/en/113/

chore(release): bump to 2.2.0
